### ISSUE TITLE
Doesn't work when deployed 

### ISSUE THREAD

**Issue by emailsubjekt** [happyharis/mahlinks#12]
I have used you example, started it and apart from a few errors in checking email validity everything went smooth when I started it as (chrome(web)) from Android Studio. However, as soon as I deployed your project so it wouldn't be local anymore but have a real internet http address, it stopped working. Instead of a login screen I got an empty screen, you can see what it looks like here: 
https://flutterrealtimedbtest186.firebaseapp.com/#/

Once again, locally, everything works, I logged in, used the add button to add some entries, they showed up on the right as if they're coming up on a cellphone that you made as part of the project with your image top right. However, as soon as I deployed the project to a web address so anyone can see it (URL ABOVE), the page is blank and nothing is showing at all. Please help.

**Comment by happyharis** [comment]
Have you tried running this command: `flutter run -d chrome --release`?

**Comment by emailsubjekt** [comment]
Using 'flutter run -d chrome --release' just runs it in chrome locally. I've tried it anyway, locally it builds ok, it works right, the sign in the crud operations, everything. But when I do firebase deploy so it has an http address so anyone can access it, it's still a blank page.

**Comment by happyharis** [comment]
Do you have a link of your project? From the information I am getting, there isn't much I can help with.

**Comment by emailsubjekt** [comment]
> Do you have a link of your project? From the information I am getting, there isn't much I can help with.
It's the same as your project, nothing is different. Are you telling me that you've tried to deploy it on the web so it has an http address and it works?

**Comment by happyharis** [comment]
Alright, I have pulled the project from latest `master` branch from my end (no changes) and deployed it [here](https://linktree-clone.firebaseapp.com/#/haris). I don't see any blank pages. Try deleting your current project and getting the latest master.

**Comment by emailsubjekt** [comment]
The CRUD operations don't work. Putting string on the firebase server and getting them back doesn't work. 

Having a simple layout on the web works, but CRUD OPERATIONS DO NOT WORK.

**Comment by happyharis** [comment]
I assume that you are able to deploy it on firebase hosting as this thread is pertaining deployment problem[current issue](https://github.com/happyharis/mahlinks/issues/12). If you have an issue that is not related to deployment, [open another issue](https://github.com/happyharis/mahlinks/issues/new/choose). I will close this for now as it is working on my end.
